# Game Settings
CONST_STARTING_CASH = 1000000  # 1500
CONST_GO_CASH = 200

CONST_HOUSE_MAX = 32
CONST_HOTEL_MAX = 12
CONST_MAX_DOUBLE_ROLL = 3

# Property
CONST_HOUSE_LIMIT = 4
CONST_HOTEL_LIMIT = 1

# TAX
CONST_INCOME_TAX = 200
CONST_LUXURY_TAX = 100

# Chance Cards
CONST_COLLECT_DIVIDEND = 50
CONST_GENERAL_REPAIR_HOUSE = 25
CONST_GENERAL_REPAIR_HOTEL = 100
CONST_POOR_TAX = 15
CONST_CHAIRMAN_FEE = 50
CONST_COLLECT_LOAN = 150
CONST_COLLECT_BANK_ERROR = 200
CONST_DOCTOR_FEE = 50
CONST_COLLECT_STOCK_SALE = 50
CONST_GRAND_OPERA_NIGHT = 50
CONST_COLLECT_HOLIDAY_FUND = 100
CONST_COLLECT_TAX_REFUND = 20
CONST_BIRTHDAY = 10
CONST_COLLECT_INSURANCE = 100
CONST_HOSPITAL_FEE = 100
CONST_SCHOOL_FEE = 50
CONST_STREET_REPAIR_HOUSE = 40
CONST_STREET_REPAIR_HOTEL = 115
CONST_COLLECT_CONSULTANCY_FEE = 25
CONST_COLLECT_CONTEST_PRIZE = 10
CONST_COLLECT_INHERITANCE = 100
